### ISSUE TITLE
Edge Fails to Start (Chrome Works)

### ISSUE THREAD

**Issue by jonathansampson** [MicrosoftEdge/BrowserEfficiencyTest#90]
@TychosNose This is following your most recent commit. I _pulled_ down the changes, rebuilt the BrowserEfficiencyTest solution, and attempted to run the tests.

Chrome ran without issue. Once an Edge window opens, the executable gets terminated. Perhaps this is an issue with the 15063 MicrosoftWebDriver executable, rather than the BrowserEfficiencyTest solution?
```
PS C:\Users\jjdsa\Desktop\Battery Tests\BrowserEfficiencyTest\BrowserEfficiencyTest\bin\Debug> ./BrowserEfficiencyTest.exe -b edge chrome -i 2 -rp C:\Traces -ms cpuUsage -s FastScenario WikipediaUnitedStates
BrowserEfficiencyTest Version: 11.1.0.0
[2017-05-25 10:21:50] --- OS Version ------
[2017-05-25 10:21:50]   BuildLabEx: 15063.0.x86fre.rs2_release.170317-1834
[2017-05-25 10:21:50]   EditionID: Professional
[2017-05-25 10:21:50]   ProductName: Windows 10 Pro
[2017-05-25 10:21:50] ---------------------
[2017-05-25 10:21:50] Pausing before starting first tracing session to reduce interference.
Attempting to connect with the trace controller...
Successfully connected to trace controller.
[2017-05-25 10:22:02] Starting Test Pass
[2017-05-25 10:22:02] Iteration: 0 ------------------
[2017-05-25 10:22:03]  Launching Browser Driver: 'chrome'
Starting ChromeDriver 2.29.461591 (62ebf098771772160f391d75e589dc567915b233) on port 52474
Only local connections are allowed.
[2017-05-25 10:22:08]   Executing - Scenario: FastScenario  Iteration: 0  Attempt: 0  Browser: chrome  MeasureSet: cpuUsage
[2017-05-25 10:22:10]     Scenario FastScenario returned in 1.5099187 seconds. Sleep for remaining 8.4900813 seconds.
[2017-05-25 10:22:18]   Completed - Scenario: FastScenario  Iteration: 0  Attempt: 0  Browser: chrome  MeasureSet: cpuUsage
[2017-05-25 10:22:18]  New Tab: Attempting to create a new tab using the javascript method window.open()
[2017-05-25 10:22:20]   Executing - Scenario: WikipediaUnitedStates  Iteration: 0  Attempt: 0  Browser: chrome  MeasureSet: cpuUsage
[2017-05-25 10:22:41]     Scenario WikipediaUnitedStates returned in 22.8342525 seconds. Sleep for remaining 7.1657475 seconds.
[2017-05-25 10:22:48]   Completed - Scenario: WikipediaUnitedStates  Iteration: 0  Attempt: 0  Browser: chrome  MeasureSet: cpuUsage
[2017-05-25 10:22:48]  SUCCESS!  Completed Browser: chrome  Iteration: 0  Attempt: 0  MeasureSet: cpuUsage
[2017-05-25 10:22:48]   Pausing between tracing sessions to reduce interference.
[2017-05-25 10:23:08]  Launching Browser Driver: 'edge'
[10:23:08.195] - Listening on http://localhost:52534/

Unhandled Exception: System.IO.FileNotFoundException: MicrosoftWebDriver.exe
   at System.Diagnostics.FileVersionInfo.GetVersionInfo(String fileName)
   at BrowserEfficiencyTest.RemoteWebDriverExtension.CreateDriverAndMaximize(String browser, String browserProfilePath) in C:\Users\jjdsa\Desktop\Battery Tests\BrowserEfficiencyTest\BrowserEfficiencyTest\RemoteWebDriverExtension.cs:line 327
   at BrowserEfficiencyTest.ScenarioRunner.Run() in C:\Users\jjdsa\Desktop\Battery Tests\BrowserEfficiencyTest\BrowserEfficiencyTest\ScenarioRunner.cs:line 213
   at BrowserEfficiencyTest.Program.Main(String[] args) in C:\Users\jjdsa\Desktop\Battery Tests\BrowserEfficiencyTest\BrowserEfficiencyTest\Program.cs:line 46
PS C:\Users\jjdsa\Desktop\Battery Tests\BrowserEfficiencyTest\BrowserEfficiencyTest\bin\Debug>
```

**Comment by TychosNose** [comment]
@jonathansampson, its the FileVersionInfo method. It can't find MicrosoftWebDriver.exe. I'll remove this. A workaround would be to move MicrosoftWebDriver.exe into the same folder that BrowserEfficiencyTest.exe is in.

**Comment by jonathansampson** [comment]
@TychosNose I'm happy to move the executable into the same directory as the BrowserEfficiencyText.exe file; this seems like a new requirement, however. Prior to today, I believe Edge worked as-is. May want to update documentation.

**Comment by TychosNose** [comment]
@jonathansampson I've merged the fix for this. With the fix, you don't need to move MicrosoftWebDriver.exe into the same folder. That was just a workaround for the issue you found.

**Comment by TychosNose** [comment]
Closing this issue.
